name = equippable_accessories
description = A mod that adds accessories you can equip
optional_depends = default,bones,pova,player_monoids,unified_inventory,moreores,mobs,farming,wool,sfinv,unified_inventory,dungeon_loot,moreores,mcl_inventory,mcl_core,mcl_armor,mcl_deepslate,mcl_blackstone,mcl_nether,playerphysics,mcl_sounds
title = Equippable Accessories
author = davidthecreator/SilverD00D
